version: "3.3"

#Define services
services:

  mysql-db:
    image: mysql:8
    container_name: mysqldb
    #Environment variable for password and default database
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'achatdb'
    ports:
      - target: 3306
        published: 3306
        protocol: tcp #Forwars the exposed port 3306 on the container to port 3306 on the host machine
    volumes:
      - /home/mysql/data:/home/vagrant/mysql:rw
  #Back-end Spring Boot Application
  springboot-app:
    #The docker file in BE, build the jar and provides the docker image.
    image: saifajengui/springbootachat1:latest
    container_name: tpachatproject
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/tpachato?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: tpachato
    restart: on-failure
    #Environment variable for Spring Boot Application.
    ports:
      - 8089:8089 #Forwars the exposed port 8080 on the container to port 8080 on the host machine
    links:
      - mysqldb
