version: "3"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=tpachtoo
      - MYSQL_USER=root
      - MYSQL_PASSWORD=admin
    volumes:
      - /var/lib/mysql

  spring_app:
    image: fatma1998/tpachat
    container_name: tpachatspring
    restart: on-failure
    environment:
      - spring.datasource.url=jdbc:mysqldb://mysql://localhost:3306/tpachtoo?createDatabaseIfNotExist=true
    ports:
      - 8089:8089
    depends_on:
      - mysqldb