version: '3.9'
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8
    volumes:
      - /home/mysql/data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
  
  spring_app:
    container_name: tpachatproject
    depends_on:
      - mysqldb
    image: tpachatproject
    ports:
      - "9090:9090"
    restart: on-failure
  

